server:
  port: 7081
  servlet:
    context-path: /uniportal
    session:
      timeout: 30m
      cookie:
        path: /
        http-only: true

logging:
  level:
    root: info
    com.unicore.mapper: info
    org.mybatis: info
  file:
    name: /home/unicore/logs/unicore.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 20MB

spring:
  application:
    name: unicore
    multipart:
      allowFormat: doc,docx,xls,xlsx,ppt,pptx,pdf,jpg,gif,jpeg,png,txt,log,wmv,mp4,zip,rar,apk,bmp,avi
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  output:
    ansi:
      enabled: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/unicore?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.10.147:3306/pms_scen_new?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 200
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.unicore.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: valiFlag
      logic-delete-value: 0
      logic-not-delete-value: 1

security:
  type: unicore-sso
  oauth2:
    client:
      permits: /,/index.html,/home,/home/**,/login,/logout,/user/forceLogout**,/captcha,/assets/**,/favicon.ico,/doc.html,/swagger-ui.html,/swagger-ui.html/**,/webjars/**,/*/api-docs,/v2/**,/**/swagger-resources,/**/swagger-resources/configuration/ui,/**/swagger-resources/configuration/security,/api/sys/config/key/**

cacheLevel: "HPM:"
cache:
  alone:
    deployType: 1
    cacheName: defaultCache
    clusterNodes: 127.0.0.1:6379
    password: 123456
  cluster:
    deployType: 2
    cacheName: defaultCache
    clusterNodes: 127.0.0.1:6379
    password: 123456
    maxRedirects: 3

session:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 5
    timeout: 6000
    pool:
      maxIdle: 50
      maxTotal: 100
      maxWaitMillis: -1
      testOnBorrow: true
      testOnReturn: true

threadPool:
  commPool:
    desc: '公共线程池'
    corePoolSize: 8
    maxPoolSize: 64
    queueCapacity: 500
    keepAliveSeconds: 60
    threadNamePrefix: unicore-task-

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: unicore